# Generated by Django 2.1.5 on 2019-02-11 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BCDApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coehead',
            name='COE_Email',
            field=models.CharField(max_length=50),
        ),
    ]
