# Generated by Django 2.1.5 on 2019-02-11 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BCDApp', '0002_auto_20190211_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='bcd',
            name='FirstApproval',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='BCDs', to='BCDApp.COEHead', verbose_name='1st Approver '),
        ),
    ]
