# Generated by Django 2.0.3 on 2019-02-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BCDApp', '0003_bcd_firstapproval'),
    ]

    operations = [
        migrations.AddField(
            model_name='bcd',
            name='COE_Comments',
            field=models.CharField(default='ok', max_length=50),
            preserve_default=False,
        ),
    ]
