# Generated by Django 2.0.3 on 2019-02-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BCDApp', '0004_bcd_coe_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='bcd',
            name='COE_status',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bcd',
            name='Finance_Comments',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bcd',
            name='Finance_status',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bcd',
            name='COE_Comments',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
