# Generated by Django 2.0.3 on 2019-02-14 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BCDApp', '0005_auto_20190214_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bcd',
            name='pdf',
            field=models.FileField(upload_to='docs/', verbose_name='Upload BCD'),
        ),
    ]
