# Generated by Django 2.0.3 on 2019-02-14 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BCDApp', '0006_auto_20190214_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bcd',
            name='COE_Comments',
            field=models.CharField(max_length=50, null=True, verbose_name='COE Comments'),
        ),
        migrations.AlterField(
            model_name='bcd',
            name='Finance_Comments',
            field=models.CharField(max_length=50, null=True, verbose_name='Finance Comments'),
        ),
    ]
