# Generated by Django 2.0.3 on 2019-02-28 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BCDApp', '0011_pr'),
    ]

    operations = [
        migrations.CreateModel(
            name='PRGrid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_Name', models.CharField(max_length=50)),
                ('Item_Description', models.CharField(max_length=250)),
                ('Quantity', models.CharField(max_length=250)),
                ('Vendor_name', models.CharField(max_length=50)),
                ('PR_No', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PR', to='BCDApp.PR')),
            ],
        ),
    ]
