# Generated by Django 2.0.3 on 2019-02-28 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BCDApp', '0012_prgrid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prgrid',
            old_name='Vendor_name',
            new_name='Bid1',
        ),
        migrations.AddField(
            model_name='prgrid',
            name='Bid2',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prgrid',
            name='Bid3',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prgrid',
            name='Budget_code',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prgrid',
            name='Tech_spoc',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prgrid',
            name='Vendor1_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prgrid',
            name='Vendor2_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prgrid',
            name='Vendor3_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prgrid',
            name='end_date',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prgrid',
            name='new_unit_rate',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prgrid',
            name='old_unit_rate',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prgrid',
            name='procurement_type',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prgrid',
            name='start_date',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prgrid',
            name='type_of_expense',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prgrid',
            name='vendor_type',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
