# Generated by Django 2.0.3 on 2019-02-28 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BCDApp', '0013_auto_20190228_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pr',
            name='Request_date',
            field=models.CharField(max_length=30),
        ),
    ]
