# Generated by Django 2.0.3 on 2019-03-01 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BCDApp', '0014_auto_20190228_1651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prgrid',
            old_name='Bid1',
            new_name='Bid_1',
        ),
        migrations.RenameField(
            model_name='prgrid',
            old_name='Bid2',
            new_name='Bid_2',
        ),
        migrations.RenameField(
            model_name='prgrid',
            old_name='Bid3',
            new_name='Bid_3',
        ),
        migrations.RenameField(
            model_name='prgrid',
            old_name='Vendor1_name',
            new_name='Vendor_1',
        ),
        migrations.RenameField(
            model_name='prgrid',
            old_name='Vendor2_name',
            new_name='Vendor_2',
        ),
        migrations.RenameField(
            model_name='prgrid',
            old_name='Vendor3_name',
            new_name='Vendor_3',
        ),
    ]
