# Generated by Django 2.0.3 on 2019-03-01 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BCDApp', '0015_auto_20190301_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pr',
            name='BCD_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PRs', to='BCDApp.BCD'),
        ),
    ]
