# Generated by Django 2.0.3 on 2019-03-01 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BCDApp', '0016_auto_20190301_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='bcd',
            name='isPRRaised',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='prgrid',
            name='PR_No',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Grids', to='BCDApp.PR'),
        ),
    ]
