# Generated by Django 2.1.5 on 2019-03-12 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BCDApp', '0017_auto_20190301_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='bcd',
            name='Final_Comments',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bcd',
            name='Final_status',
            field=models.CharField(default='NA', max_length=30),
        ),
    ]
