# Generated by Django 2.1.5 on 2019-03-12 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BCDApp', '0018_auto_20190312_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='GovHead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gov_ID', models.CharField(max_length=30)),
                ('Gov_Name', models.CharField(max_length=30)),
                ('Gov_Email', models.CharField(max_length=50)),
            ],
        ),
    ]
