# Generated by Django 2.1.5 on 2019-03-12 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BCDApp', '0019_govhead'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pr',
            old_name='End_date',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='pr',
            old_name='Start_date',
            new_name='start_date',
        ),
    ]
