# Generated by Django 2.1.5 on 2019-03-13 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BCDApp', '0022_auto_20190312_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prgrid',
            name='Item_Description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='prgrid',
            name='Item_Name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
