# Generated by Django 2.1.5 on 2019-04-26 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BCDApp', '0024_auto_20190313_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bcd',
            name='BCD_amount',
            field=models.CharField(max_length=8),
        ),
    ]
