# Generated by Django 2.1.5 on 2019-04-26 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BCDApp', '0025_auto_20190426_0618'),
    ]

    operations = [
        migrations.AddField(
            model_name='bcd',
            name='BCD_reference_no',
            field=models.CharField(default='NA', max_length=30),
            preserve_default=False,
        ),
    ]
