# Generated by Django 2.1.5 on 2019-04-26 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BCDApp', '0026_bcd_bcd_reference_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='bcd',
            name='is_reffered',
            field=models.BooleanField(default='0'),
            preserve_default=False,
        ),
    ]
