# Generated by Django 2.1.5 on 2019-04-26 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BCDApp', '0027_bcd_is_reffered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bcd',
            old_name='BCD_overview',
            new_name='BCD_summary',
        ),
    ]
