# Generated by Django 2.1.5 on 2019-04-30 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BCDApp', '0028_auto_20190426_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bcd',
            name='is_reffered',
            field=models.BooleanField(default=False),
        ),
    ]
