# Generated by Django 2.1.5 on 2019-05-02 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BCDApp', '0029_auto_20190430_0605'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.AlterField(
            model_name='pr',
            name='Budget',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Budgets', to='BCDApp.Budget', verbose_name='Budget'),
        ),
    ]
