# Generated by Django 2.1.5 on 2019-05-02 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BCDApp', '0030_auto_20190502_0829'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget_Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_code', models.CharField(max_length=25)),
                ('budget_desc', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Type_of_Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_expense', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='prgrid',
            name='Budget_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='BudgetCodes', to='BCDApp.Budget_Code', verbose_name='Budget Code'),
        ),
        migrations.AlterField(
            model_name='prgrid',
            name='Quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='prgrid',
            name='type_of_expense',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type_of_expenses', to='BCDApp.Type_of_Expense', verbose_name='Type_of_Expense'),
        ),
    ]
