# Generated by Django 2.1.5 on 2019-05-02 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BCDApp', '0032_auto_20190502_0845'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procurement_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procurement_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='prgrid',
            name='procurement_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ProcurementTypes', to='BCDApp.Procurement_Type', verbose_name='Procurement Types'),
        ),
        migrations.AlterField(
            model_name='prgrid',
            name='vendor_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='VendorTypes', to='BCDApp.Vendor_Type', verbose_name='Vendor Type'),
        ),
    ]
